trigger:
  - master

jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: ci/azure-steps.yml
    strategy:
      matrix:
        x86_64:
          TARGET: x86_64-unknown-linux-gnu
          DOCKER: linux64
        i686:
          TARGET: i686-unknown-linux-gnu
          DOCKER: linux32
        x86_64-musl:
          TARGET: x86_64-unknown-linux-musl
          DOCKER: musl
        mingw:
          TARGET: x86_64-pc-windows-gnu
          DOCKER: mingw
          NO_RUN: 1
          TOOLCHAIN: nightly
        system-curl:
          TARGET: x86_64-unknown-linux-gnu
          DOCKER: linux64-curl
        openssl-110:
          TARGET: x86_64-unknown-linux-gnu
          DOCKER: centos7
        x86_64-beta:
          TARGET: x86_64-unknown-linux-gnu
          DOCKER: linux64
          TOOLCHAIN: beta
        x86_64-nightly:
          TARGET: x86_64-unknown-linux-gnu
          DOCKER: linux64
          TOOLCHAIN: nightly

  - job: macOS
    pool:
      vmImage: macos-10.13
    steps:
      - template: ci/azure-steps.yml
    strategy:
      matrix:
        x86_64:
          TARGET: x86_64-apple-darwin
        i686:
          TARGET: i686-apple-darwin

  - job: macOS_static
    pool:
      vmImage: macos-10.13
    steps:
      - checkout: self
        submodules: true
      - template: ci/azure-install-rust.yml
      - script: cargo test --features curl-sys/static-curl -vvv

  - job: Windows_vs2019
    pool:
      vmImage: windows-2019
    steps:
      - template: ci/azure-steps.yml
    strategy:
      matrix:
        x86_64-msvc:
          TARGET: x86_64-pc-windows-msvc

  - job: Windows_vs2017
    pool:
      vmImage: vs2017-win2016
    steps:
      - template: ci/azure-steps.yml
    strategy:
      matrix:
        x86_64-msvc:
          TARGET: x86_64-pc-windows-msvc
        i686-msvc:
          TARGET: i686-pc-windows-msvc

  - job: Windows_vs2015
    pool:
      vmImage: vs2015-win2012r2
    steps:
      - template: ci/azure-steps.yml
    strategy:
      matrix:
        x86_64-msvc:
          TARGET: x86_64-pc-windows-msvc

  - job: docs
    steps:
      - template: ci/azure-install-rust.yml
      - script: cargo doc --no-deps --all-features
      - script: curl -LsSf https://git.io/fhJ8n | rustc - && (cd target/doc && ../../rust_out)
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        env:
          GITHUB_DEPLOY_KEY: $(GITHUB_DEPLOY_KEY)
